-- @description Aligner item sous souris sur item selectionné (Natif)
-- @version 2.0
-- @author Generated by Gemini
-- @about
--   Aligns the item under the mouse to the selected item position.
--   Works without SWS extensions.
--   Respects Snap Offsets (points de synchro).

function main()
  -- 1. Récupérer l'item sous la souris (Méthode Native)
  -- On récupère les coordonnées de la souris sur l'écran
  local x, y = reaper.GetMousePosition()
  -- On demande à Reaper quel item se trouve à ces coordonnées
  local item_under_mouse = reaper.GetItemFromPoint(x, y, true)

  if not item_under_mouse then 
    -- Si on clique dans le vide, on arrête
    return 
  end

  -- 2. Récupérer l'item de référence parmi les items sélectionnés.
  -- On prend le PREMIER item sélectionné qui n'est PAS celui sous la souris,
  -- pour gérer le cas où plusieurs items sont sélectionnés et l'utilisateur
  -- clique sur l'un d'entre eux : on s'aligne sur les autres, pas sur soi-même.
  local n_selected = reaper.CountSelectedMediaItems(0)
  if n_selected == 0 then
    return
  end

  local selected_item = nil
  for i = 0, n_selected - 1 do
    local cand = reaper.GetSelectedMediaItem(0, i)
    if cand ~= item_under_mouse then
      selected_item = cand
      break
    end
  end

  if not selected_item then
    -- Le seul item sélectionné est celui sous la souris : rien à aligner
    return
  end

  -- 3. Calculs et Déplacement
  reaper.Undo_BeginBlock()

  -- A. Référence (Audio 1) : Position absolue du point de synchro
  local pos_ref = reaper.GetMediaItemInfo_Value(selected_item, "D_POSITION")
  local snap_ref = reaper.GetMediaItemInfo_Value(selected_item, "D_SNAPOFFSET")
  local sync_point_ref = pos_ref + snap_ref

  -- B. Cible (Audio 2) : Récupérer son Snap Offset pour calculer le recul nécessaire
  local snap_target = reaper.GetMediaItemInfo_Value(item_under_mouse, "D_SNAPOFFSET")

  -- C. Calcul de la nouvelle position (Point de synchro - Snap Offset de la cible)
  local new_pos = math.max(0, sync_point_ref - snap_target)

  -- 4. Appliquer
  reaper.SetMediaItemInfo_Value(item_under_mouse, "D_POSITION", new_pos)
  
  -- 5. Rafraîchir l'affichage
  reaper.UpdateArrange()
  reaper.Undo_EndBlock("Aligner item sous souris", -1)
end

-- Exécution
reaper.defer(main)